### ISSUE TITLE
Description for View

### ISSUE THREAD

**Issue by damianoneill** [Shyamranny/spring-data-rest-couchbase#1]
I was looking at your sample project, I'm not familiar with Couchbase or how Spring Data Couchbase interacts with it.  

Could you explain how to setup Couchbase to you work with your sample?  Specifically this statement from the exception: 

```
Could not load view "all" for design doc "user"
```

Thanks in advance.
Damian.

```
2017-03-09 21:36:40.333 ERROR 67837 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: Could not load view "all" for design doc "user"; nested exception is com.couchbase.client.protocol.views.InvalidViewException: Could not load view "all" for design doc "user"] with root cause

com.couchbase.client.protocol.views.InvalidViewException: Could not load view "all" for design doc "user"
	at com.couchbase.client.CouchbaseClient.getView(CouchbaseClient.java:433) ~[couchbase-client-1.4.7.jar!/:1.4.7]
	at org.springframework.data.couchbase.core.CouchbaseTemplate$2.doInBucket(CouchbaseTemplate.java:225) ~[spring-data-couchbase-1.4.4.RELEASE.jar!/:na]
	at org.springframework.data.couchbase.core.CouchbaseTemplate$2.doInBucket(CouchbaseTemplate.java:222) ~[spring-data-couchbase-1.4.4.RELEASE.jar!/:na]
	at org.springframework.data.couchbase.core.CouchbaseTemplate.execute(CouchbaseTemplate.java:246) ~[spring-data-couchbase-1.4.4.RELEASE.jar!/:na]
	at org.springframework.data.couchbase.core.CouchbaseTemplate.queryView(CouchbaseTemplate.java:222) ~[spring-data-couchbase-1.4.4.RELEASE.jar!/:na]
	at org.springframework.data.couchbase.core.CouchbaseTemplate.findByView(CouchbaseTemplate.java:210) ~[spring-data-couchbase-1.4.4.RELEASE.jar!/:na]
	at org.springframework.data.couchbase.repository.support.SimpleCouchbaseRepository.findAll(SimpleCouchbaseRepository.java:133) ~[spring-data-couchbase-1.4.4.RELEASE.jar!/:na]
```

**Comment by Shyamranny** [comment]
Hi, I have limited access to internet. So I can't check it online. If I
remember correctly, you need to create a default view in couchbase. Please
paste the exact exception in google, which will guide you.
